[package]
name = "ui"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { workspace = true }
api = { workspace = true }
ti_helper_game_data = { workspace = true }
strum = { workspace = true, features = ["derive"] }
dioxus-free-icons = { version = "0.10.0", features = ["font-awesome-solid"] }
chrono = "0.4.42"
dioxus-sdk = "0.7.0"

[features]
server = ["api/server"]
